language: node_js

node_js:
 - "0.10"

services:
 - mysql

notifications:
  email:
    - jrgm@mozilla.com

install:
  - npm run-script dumpnpmenv
  - 'ls -la /home/travis/.npm || true'
  - 'cat /home/travis/.nvm/v0.10.26/etc/npmrc || true'
  - 'cat /home/travis/.npmrc || true'
  - 'cat /home/travis/.nvm/v0.10.26/etc/npmignore || true'
  - 'cat /home/travis/.npm-init.js || true'
  - npm install --no-optional

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'

script:
  - npm test
