language: node_js

node_js:
 - "0.10"

services:
 - mysql

notifications:
  email:
    - jrgm@mozilla.com

install:
  - npm install --no-optional

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'

script:
  - npm test
