language: node_js

node_js:
 - "0.10"

services:
 - mysql

notifications:
  email:
    - jrgm@mozilla.com

install:
  - npm run-script dumpnpmenv
  - ls -la /home/travis/.npm
  - cat /home/travis/.nvm/v0.10.26/etc/npmrc
  - cat /home/travis/.npmrc
  - cat /home/travis/.nvm/v0.10.26/etc/npmignore
  - cat /home/travis/.npm-init.js
  - npm install --no-optional

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'

script:
  - npm test
